proxies:  
- name: ORBIT_TEST
  type: vmess
  server: sanggoro-bogor2.bypass.id
  port: 80
  uuid: db2d5fc0-6807-11ed-8d7c-1577c1651679
  alterId: 0
  cipher: auto
  udp: true
  skip-cert-verify: true
  tls: false
  network: ws
  ws-opts:
   path: /kuota-habis/
   headers:
    Host: myorbit.id
